version: "2"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/apps/api
    working_dir: /go/src/apps/api
    # command: go run main.go
    command: fresh
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=130779
      - MYSQL_ROOT_PASSWORD=130779
      - MYSQL_DATABASE=api