version: "2"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - db:database
    volumes:
      - .:/go/src/github.com/weebagency/go-api
    working_dir: /go/src/github.com/weebagency/go-api
    # command: go run main.go
    command: fresh
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=api